#!/bin/bash

#Variables, with some default values

DOCROOT="/var/www"
DOMAIN=""
HTOPATH=$(dirname $0)
SFTP="false"

#Usage

function help() {
  
  echo -e "\r\nUsage:
  -d, --docroot\t Global directory for DocumentRoots (/var/www)
  -s, --sftp\t Enable SFTP Access for this Domain (separated user is required!)         
  -h, --help\t Print this help
  "  
  exit 0

}

#Error handling

function missing_arg() {

  echo -e "$0: ERROR: Missing argument for $1\r\n"
  exit 1

}

function external_error() {

  if [ "$?" -ne 0 ]
  then

    exit 1

  fi

}

#Main functions

function createdomain() {

  FULLDOMAIN=$1
  DOMAIN=${1//[-._]/}

  #Create User
  useradd -s /bin/false -d $DOCROOT/$DOMAIN/htdocs $DOMAIN
  adduser www-data $DOMAIN

  #Create folders
  mkdir -p $DOCROOT/$DOMAIN/htdocs/public
  mkdir $DOCROOT/$DOMAIN/logs
  mkdir $DOCROOT/$DOMAIN/conf
  mkdir $DOCROOT/$DOMAIN/sessions
  mkdir $DOCROOT/$DOMAIN/tmp

  #Create SFTP-Access
  if [ $SFTP = "true" ]
  then

    $HTOPATH/htoweb-allowsftp $DOMAIN
    external_error

  fi

  #Create VirtualHost config
  $HTOPATH/htoweb-createvhost $FULLDOMAIN
  external_error

  #Create FCGID Wrapper Script
  echo -e "#!/bin/sh" >> $DOCROOT/$DOMAIN/conf/fcgid
  echo -e 'export PHPRC="$DOCROOT/$DOMAIN/conf/"' >> $DOCROOT/$DOMAIN/conf/fcgid
  echo -e "exec /usr/bin/php5-cgi" >> $DOCROOT/$DOMAIN/conf/fcgid

  #Create php.ini
  $HTOPATH/htoweb-createphpini -d $DOCROOT $DOMAIN 
  external_error

  #Set owners to dirs/files
  chown root:$DOMAIN $DOCROOT/$DOMAIN
  chown $DOMAIN:$DOMAIN $DOCROOT/$DOMAIN/*
  chown root:root $DOCROOT/$DOMAIN/logs
  chown root:$DOMAIN $DOCROOT/$DOMAIN/conf/php.ini
  chown $DOMAIN:$DOMAIN $DOCROOT/$DOMAIN/conf/fcgid
  
  #Set permissions to dirs/files
  chmod 750 $DOCROOT/$DOMAIN
  chmod 750 $DOCROOT/$DOMAIN/*
  chmod 640 $DOCROOT/$DOMAIN/conf/php.ini
  chmod 750 $DOCROOT/$DOMAIN/conf/fcgid
  chmod 750 $DOCROOT/$DOMAIN/htdocs

  #Run htoweb-updateprivs
  $HTOPATH/htoweb-updateprivs -d $DOCROOT $DOMAIN
  external_error

  #Enable VirtualHost and reload Apache
  a2ensite $DOMAIN
  /etc/init.d/apache2 reload

  exit 0

}

#Command Line Options

if [ "$#" -eq "0" ]
then

  help

elif [ "$#" -eq "1" ]
then

  if [ "$1" = "-h" -o "$1" = "--help" ]
  then
      
    help
    
  fi

  createdomain $1

fi

while [ "$#" -gt "1" ]
do

  case $1 in

    -d|--docroot)
      if [[ "$#" -ge 2 && "$2" != -* ]]
      then
 
        DOCROOT=$2
        shift 2

      else
      
        missing_arg $1

      fi
      ;;

    -s|--sftp)

      SFTP="true"
      shift 1
    ;;

    -h|--help)
      help
      ;;

    *)
      echo -e "ERROR: Unknown option $1\r\n"
      exit 1
      ;;

  esac

done

createdomain $1 $DOCROOT
