#!/bin/bash

#Define variables, some have default values

DOCROOT="/var/www"

#Main functions

function create_phpini() {

cat >> $DOCROOT/$DOMAIN/conf/php.ini << EOC
open_basedir = $DOCROOT/$DOMAIN/htdocs/public:$DOCROOT/$DOMAIN/tmp/
upload_tmp_dir = $DOCROOT/$DOMAIN/tmp
soap.wsdl_cache_dir = $DOCROOT/$DOMAIN/tmp
session.save_path = $DOCROOT/$DOMAIN/sessions
EOC

}

#Command line options

if [ "$#" -eq 0 ]
then

  echo -e "$0: ERROR: No options given.\r\n"
  exit 1

fi

while [ "$#" -gt 1 ]
do

  case $1 in

    -d|--docroot)
      if [[ "$#" -ge 2 && "$2" != -* ]]
      then

        DOCROOT=$2

      else

        echo -e "$0: ERROR: Missing argument for $1\r\n"
        exit 1

      fi
      shift 2
      ;;

    -h|--help)
      help
      ;;

    *)
      echo -e "$0: ERROR: Unknown option $1\r\n"
      exit 1
      ;;

  esac

done

DOMAIN=${1//[-._]/}

create_phpini $DOMAIN $DOCROOT
